version: '3.9'
services:
  st-react:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    container_name: st-react
    volumes:
       - .:/usr/src/simple-twitch-react
    command: [npm, start]