
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';
export const FETCH_CATEGORIES_FAIL = 'FETCH_CATEGORIES_FAIL';

export const FETCH_CHANNELS_SUCCESS = 'FETCH_CHANNELS_SUCCESS';
export const FETCH_CHANNELS_FAIL = 'FETCH_CHANNELS_FAIL';

export const UPDATE_HEADER_HEIGHT = 'UPDATE_HEADER_HEIGHT';
export const UPDATE_HEADER_CHANNEL_WIDTH = 'UPDATE_HEADER_CHANNEL_WIDTH';